# Generated by Django 5.0.6 on 2024-05-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_obra_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='obra',
            name='historia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='obra',
            name='id_obra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
