# Generated by Django 5.0.6 on 2024-05-20 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto_alter_empleado_genero_alter_empleado_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.empleado'),
        ),
    ]
