# Generated by Django 5.0.1 on 2024-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_obra_id_alter_obra_id_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='tecnica_usada',
            field=models.CharField(max_length=350),
        ),
    ]
