# Generated by Django 5.0.6 on 2024-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_obra_tecnica_usada'),
    ]

    operations = [
        migrations.CreateModel(
            name='voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Plan Básico'), ('standard', 'Plan Estándar'), ('premium', 'Plan Premium')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
