# Generated by Django 5.0.6 on 2024-06-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_voucher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='voucher',
            new_name='Order',
        ),
    ]
