# Generated by Django 5.0.6 on 2024-06-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_venta', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_plan', models.CharField(max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
