# Generated by Django 5.0.6 on 2024-06-28 06:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='foto'),
        ),
    ]
